<?php

declare(strict_types=1);

namespace Ghuraghuri\Api\Data;

/**
 * Loads api/data/places.json (generated by tools/export-places.js) so the API
 * can resolve destinations/districts/divisions to coordinates and offer
 * Bangla+English autocomplete without any external dependency.
 */
final class PlacesRepository
{
    private array $data;

    public function __construct()
    {
        $file = GHURAGHURI_API_DIR . '/data/places.json';
        $this->data = is_file($file)
            ? (json_decode((string) file_get_contents($file), true) ?? [])
            : ['divisions' => [], 'districts' => [], 'destinations' => []];
    }

    public function destinations(): array
    {
        return $this->data['destinations'] ?? [];
    }

    public function districts(): array
    {
        return $this->data['districts'] ?? [];
    }

    public function divisions(): array
    {
        return $this->data['divisions'] ?? [];
    }

    /**
     * Find the closest destination by (name, slug) or a fuzzy prefix.
     */
    public function findDestination(string $query): ?array
    {
        $q = mb_strtolower(trim($query));
        if ($q === '') {
            return null;
        }
        $best = null;
        foreach ($this->destinations() as $d) {
            $name = mb_strtolower((string) $d['name']);
            $nameBn = mb_strtolower((string) ($d['name_bn'] ?? ''));
            $slug = mb_strtolower((string) $d['slug']);
            if ($slug === $q || $name === $q || ($nameBn !== '' && $nameBn === $q)) {
                return $d;
            }
            if ($best === null && (str_starts_with($name, $q) || ($nameBn !== '' && str_starts_with($nameBn, $q)))) {
                $best = $d;
            }
        }
        return $best;
    }

    public function findDistrict(string $query): ?array
    {
        $q = mb_strtolower(trim($query));
        foreach ($this->districts() as $d) {
            $name = mb_strtolower((string) $d['name']);
            $nameBn = mb_strtolower((string) ($d['name_bn'] ?? ''));
            if ($name === $q || ($nameBn !== '' && $nameBn === $q)) {
                return $d;
            }
        }
        return null;
    }

    public function findDivision(string $query): ?array
    {
        $q = mb_strtolower(trim($query));
        foreach ($this->divisions() as $d) {
            if (mb_strtolower((string) $d['name']) === $q) {
                return $d;
            }
        }
        return null;
    }

    /**
     * Resolve a location string to coordinates by trying destination ->
     * district -> division, returning null when unknown.
     *
     * @return array{lat:float,lng:float,kind:string,name:string}|null
     */
    public function resolve(string $query): ?array
    {
        $q = trim($query);
        if ($q === '') {
            return null;
        }
        $d = $this->findDestination($q);
        if ($d !== null) {
            return [
                'lat' => (float) $d['lat'],
                'lng' => (float) $d['lng'],
                'kind' => 'destination',
                'name' => (string) $d['name'],
                'district' => (string) ($d['district'] ?? ''),
                'division' => (string) ($d['division'] ?? ''),
            ];
        }
        $di = $this->findDistrict($q);
        if ($di !== null) {
            return [
                'lat' => (float) $di['lat'],
                'lng' => (float) $di['lng'],
                'kind' => 'district',
                'name' => (string) $di['name'],
                'district' => (string) $di['name'],
                'division' => (string) ($di['division'] ?? ''),
            ];
        }
        $dv = $this->findDivision($q);
        if ($dv !== null) {
            return [
                'lat' => (float) $dv['lat'],
                'lng' => (float) $dv['lng'],
                'kind' => 'division',
                'name' => (string) $dv['name'],
                'district' => '',
                'division' => (string) $dv['name'],
            ];
        }
        return null;
    }

    /**
     * Autocomplete across destinations, districts and divisions (EN + BN).
     */
    public function autocomplete(string $query, int $limit = 10): array
    {
        $q = mb_strtolower(trim($query));
        if ($q === '') {
            return [];
        }
        $out = [];
        foreach ($this->divisions() as $d) {
            if ($this->match($d, $q)) {
                $out[] = $this->entry($d, 'division');
            }
        }
        foreach ($this->districts() as $d) {
            if ($this->match($d, $q)) {
                $out[] = $this->entry($d, 'district');
            }
        }
        foreach ($this->destinations() as $d) {
            if ($this->match($d, $q)) {
                $out[] = $this->entry($d, 'destination');
            }
            if (count($out) >= $limit) {
                break;
            }
        }
        return array_slice($out, 0, $limit);
    }

    private function match(array $d, string $q): bool
    {
        $name = mb_strtolower((string) ($d['name'] ?? ''));
        $nameBn = mb_strtolower((string) ($d['name_bn'] ?? ''));
        $slug = mb_strtolower((string) ($d['slug'] ?? ''));
        return str_starts_with($name, $q)
            || str_starts_with($slug, $q)
            || ($nameBn !== '' && str_starts_with($nameBn, $q))
            || str_contains($name, $q)
            || ($nameBn !== '' && str_contains($nameBn, $q));
    }

    private function entry(array $d, string $kind): array
    {
        return [
            'type' => $kind,
            'name' => (string) ($d['name'] ?? ''),
            'name_bn' => (string) ($d['name_bn'] ?? ''),
            'district' => (string) ($d['district'] ?? ''),
            'division' => (string) ($d['division'] ?? ''),
            'lat' => (float) ($d['lat'] ?? 0),
            'lng' => (float) ($d['lng'] ?? 0),
        ];
    }

    /** Haversine distance in km between two coordinates. */
    public static function distanceKm(float $lat1, float $lng1, float $lat2, float $lng2): float
    {
        $earth = 6371.0;
        $dlat = deg2rad($lat2 - $lat1);
        $dlng = deg2rad($lng2 - $lng1);
        $a = sin($dlat / 2) ** 2 + cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * sin($dlng / 2) ** 2;
        return $earth * 2 * atan2(sqrt($a), sqrt(1 - $a));
    }
}